name: 'sap_pipeline'
version: '1.0.0'
config-version: 2

profile: 'sap_pipeline'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  sap_pipeline:
    silver:
      +materialized: table
      +schema: silver_dev
    gold:
      +materialized: table
      +schema: gold_dev